language: node_js
node_js:
  - 0.8
script: gulp test
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install -g karma
  - npm install phantomjs
  - npm install
  - bower install
  - gulp build


